apiVersion: hsmade.com/v1alpha1
kind: Minecraft
metadata:
  name: minecraft-test-1
spec:
  enabled: true
  minecraft:
    version: 1.14.4
    type: FORGE
    mods:
    - filename: cfm.jar
      url: "https://www.dropbox.com/s/4dp3mqwrqvne9na/cfm-7.0.0-pre15-mc1.14.4.jar?dl=1"
    properties: |
      difficulty=easy
      gamemode=creative
  storage:
    path: /tmp/minecraft-test-1
    size: 5Gi
  
